"""
Hidden Markov Model (HMM) Predictor
-----------------------------------
Hypothesis: The Jodi sequence is generated by a process with latent (hidden) 
states. We use a Categorical HMM to uncover these states and predict 
the most likely next emission.
"""
import pandas as pd
import numpy as np
from hmmlearn import hmm
from scipy.stats import norm
from research.tracker import log_experiment
from typing import Dict, Any, List

class HMMPredictor:
    """
    Categorical HMM for Jodi sequence prediction.
    """
    def __init__(self, n_states: int = 4):
        self.n_states = n_states
        # 100 possible Jodi outcomes (0-99)
        self.model = hmm.CategoricalHMM(n_components=n_states, n_iter=100, random_state=42)

    def train(self, series: pd.Series):
        # Reshape for hmmlearn (samples, features)
        X = series.values.reshape(-1, 1)
        self.model.fit(X)

    def predict_next_probs(self, last_jodi: int) -> np.ndarray:
        """
        Calculates P(X_{t+1} | X_t) using the HMM transition and emission matrices.
        P(X_{t+1}=j | X_t=i) = sum_k sum_m P(X_{t+1}=j | S_{t+1}=m) * P(S_{t+1}=m | S_t=k) * P(S_t=k | X_t=i)
        """
        # 1. P(S_t=k | X_t=i) - Posterior of current state given last observation
        # Note: A simple approximation is to use the state with highest emission for i
        # or use the model's posterior if we have the whole sequence.
        # For simplicity, we'll use the transition and emission directly.
        
        # Emission matrix: (states, 100)
        emissions = self.model.emissionprob_
        # Transition matrix: (states, states)
        transitions = self.model.startprob_ if last_jodi is None else self.model.transmat_
        
        # If we don't have a sequence, we use start probabilities
        # Here we just look at the most likely current states that could emit last_jodi
        state_posteriors = emissions[:, last_jodi]
        state_posteriors /= state_posteriors.sum()
        
        # Next state distribution: P(S_{t+1}) = state_posteriors * transitions
        next_state_dist = np.dot(state_posteriors, self.model.transmat_)
        
        # Next emission distribution: P(X_{t+1}) = next_state_dist * emissions
        next_emission_dist = np.dot(next_state_dist, emissions)
        
        return next_emission_dist

    def quick_backtest(self, df: pd.DataFrame, top_k: int = 10) -> Dict[str, Any]:
        jodis = pd.to_numeric(df['Jodi'], errors='coerce').dropna().astype(int).tolist()
        hits = 0
        total = 0
        
        # Minimum samples to fit HMM
        train_size = 300
        
        for i in range(train_size, len(jodis) - 1):
            # To be strictly fair, we should retrain every few days
            # but for speed in research, we fit once on history and predict.
            if i == train_size or i % 50 == 0:
                self.train(pd.Series(jodis[:i+1]))
            
            probs = self.predict_next_probs(jodis[i])
            top_preds = np.argsort(probs)[-top_k:]
            
            if jodis[i+1] in top_preds:
                hits += 1
            total += 1
            
        hit_rate = hits / total if total > 0 else 0
        baseline = top_k / 100.0
        
        # Significance
        std_error = np.sqrt((baseline * (1 - baseline)) / total) if total > 0 else 0
        z_score = (hit_rate - baseline) / std_error if std_error > 0 else 0
        p_value = 1 - norm.cdf(z_score)

        results = {
            "hit_rate": round(hit_rate, 4),
            "baseline": round(baseline, 4),
            "z_score": round(z_score, 4),
            "p_value": round(p_value, 6),
            "n_states": self.n_states,
            "total_days": total
        }
        
        log_experiment("hmm_categorical_prediction", results)
        return results

if __name__ == "__main__":
    from data.data_loader import DataLoader
    from config import DATA_FILE, SCHEMA_FILE
    loader = DataLoader(DATA_FILE, SCHEMA_FILE)
    df = loader.load_data()
    
    # Test with different state counts
    for n in [3, 6]:
        print(f"--- HMM Predictor Analysis (States: {n}) ---")
        predictor = HMMPredictor(n_states=n)
        stats = predictor.quick_backtest(df, top_k=10)
        print(f"  Hit Rate: {stats['hit_rate']:.2%} (Baseline: 10.00%)")
        print(f"  Z-Score: {stats['z_score']}")
        print(f"  P-Value: {stats['p_value']}")
